package by.tc.eq.controller.command;

public enum CommandName {

	SIGN_IN, SIGN_OUT,

	ADD_USER, UPDATE_USER_DATA, DELETE_USER,

	ADD_EQUIPMENT, UPDATE_EQUIPMENT, DELETE_EQUIPMENT,

	RENT_EQUIPMENT, RETURN_EQUIPMENT,

	GENERATE_AVAILABLE_EQUIPMENT_REPORT, GENERATE_RENTED_EQUIPMENT_REPORT, GENERATE_USER_REPORT, GENERATE_OWER_REPORT,

	WRONG_REQUEST;
}
