package by.epam.totalizator.controller.command;

public enum CommandName {

	SIGNUP_PAGE, SIGNUP, SIGNIN_PAGE, SIGNIN, SIGNOUT,

	HOME, RESULT, TOURNAMENT_PAGE,

	GET_USER_LIST, CREATE_COMPETITION, UPDATE_COMPETITION,
	
	COMPETITION_INFO, DATA_FOR_COMPETITION,

	SET_RATES, MAKE_BETTING, ADD_COMPETITION,

	USER_PROFILE, EDIT_PROFILE, USER_BETTING,

	WRONGREQUEST;
}
